name: Publish Registry to ghcr.io

env:
  DOCKER_TAG: ghcr.io/arifai/android-sdk

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  tools:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.ref }} Branch in ${{ github.repository }} Repository
        uses: actions/checkout@v4
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build ${{ github.repository }} and push to ghcr.io
        run: |
          docker build -t $DOCKER_TAG:latest -t $DOCKER_TAG:tools -f sdk/tools/Dockerfile .
          docker push $DOCKER_TAG --all-tags

  ndk:
    permissions: write-all
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [tools]
    steps:
      - name: Checkout ${{ github.ref }} Branch in ${{ github.repository }} Repository
        uses: actions/checkout@v4
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build ${{ github.repository }} and push to ghcr.io
        run: |
          docker build -t $DOCKER_TAG:ndk-26 -f sdk/ndk/Dockerfile .
          docker push $DOCKER_TAG:ndk-26