name: Publish Registry to ghcr.io

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  tools:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.ref }} Branch in ${{ github.repository }} Repository
        uses: actions/checkout@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build ${{ github.repository }} and push to ghcr.io
        uses: docker/build-push-action@v5
        with:
          context: sdk/tools/Dockerfile .
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: | 
            ghcr.io/${{ github.repository_owner }}/android-sdk:tools
            ghcr.io/${{ github.repository_owner }}/android-sdk:latest

  ndk:
    permissions: write-all
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [tools]
    steps:
      - name: Checkout ${{ github.ref }} Branch in ${{ github.repository }} Repository
        uses: actions/checkout@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build ${{ github.repository }} and push to ghcr.io
        uses: docker/build-push-action@v5
        with:
          context: sdk/ndk/Dockerfile .
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: | 
            ghcr.io/${{ github.repository_owner }}/android-sdk:ndk
            ghcr.io/${{ github.repository_owner }}/android-sdk:latest