name: Publish Registry to ghcr.io

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build_and_push:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

  tools:
    needs: [build_and_push]
    runs-on: ubuntu-latest
    steps:
      - name: Build and push tools to ghcr.io
        uses: docker/build-push-action@v5
        with:
          context: '{{defaultContext}}:sdk/tools'
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/android-sdk:tools
            ghcr.io/${{ github.repository_owner }}/android-sdk:latest

  ndk:
    permissions: write-all
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [build_and_push]
    steps:
      - name: Build and push NDK to ghcr.io
        uses: docker/build-push-action@v5
        with:
          context: '{{defaultContext}}:sdk/ndk'
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/android-sdk:ndk-26
